name: finance_app
description: "A Flutter Finance Application."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.12.1
  firebase_auth: ^6.5.6
  cloud_firestore: ^6.7.1
  intl: ^0.20.2 # 👈 Осы жерді 0.20.2-ге өзгерттік
  fl_chart: ^1.0.0
  google_fonts: ^8.1.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/assets/logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  generate: true

  assets:
    - lib/assets/logo.png